import type { ReactNode } from "react";

/**
 * The gradient-border shell every completed AI output (chat answers, Meeting
 * Brief) renders inside — this is what makes an AI output visually
 * unmistakable from an ordinary card. The "Generated by Atlas Copilot"
 * footer lives here so every wrapped surface gets it for free.
 */
export function AIResponseCard({ children, className }: { children: ReactNode; className?: string }) {
  return (
    <div
      className={`rounded-xl bg-gradient-to-br from-teal-400/50 via-cyan-400/30 to-teal-300/10 p-px dark:from-teal-500/40 dark:via-cyan-500/25 dark:to-teal-500/5 ${className ?? ""}`}
    >
      <div className="rounded-[11px] bg-white p-4 dark:bg-[#161b22]">
        {children}
        <p className="mt-3 text-[10px] text-teal-500/70 dark:text-teal-400/50">Generated by Atlas Copilot</p>
      </div>
    </div>
  );
}
